'''
Created on 04.12.2017

@author: mabelli
'''

def createWPColors(t_Color, session, CompanyID):
    session.add(t_Color(C_ID=CompanyID,
                       Name="Matt Black",
                       ID_Num="WP1101"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Necromancer Cloak",
                       ID_Num="WP1443"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Hardened Carapace",
                       ID_Num="WP1430"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Dark Stone",
                       ID_Num="WP1425"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Cultist Robe",
                       ID_Num="WP1414"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Field Grey",
                       ID_Num="WP1481"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Castle Grey",
                       ID_Num="WP1407"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Dungeon Grey",
                       ID_Num="WP1418"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Uniform Grey",
                       ID_Num="WP1118"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Ash Grey",
                       ID_Num="WP1117"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Stone Golem",
                       ID_Num="WP1455"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Spaceship Exterior",
                       ID_Num="WP1454"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Brainmatter Beige",
                       ID_Num="WP1406"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Matt White",
                       ID_Num="WP1102"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Banshee Brown",
                       ID_Num="WP1404"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Kobold Skin",
                       ID_Num="WP1434"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Hemp Rope",
                       ID_Num="WP1433"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Crusted Sore",
                       ID_Num="WP1412"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Orc Blood",
                       ID_Num="WP1422"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Grimoire Purple",
                       ID_Num="WP1444"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Warlock Purple",
                       ID_Num="WP1451"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Wasteland Soil",
                       ID_Num="WP1463"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Desert Yellow",
                       ID_Num="WP1121"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Fur Brown",
                       ID_Num="WP1122"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Skeleton Bone",
                       ID_Num="WP1125"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Barbarian Flesh",
                       ID_Num="WP1126"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Tanned Flesh",
                       ID_Num="WP1127"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Basilisk Brown",
                       ID_Num="WP1405"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Centaur Skin",
                       ID_Num="WP1408"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Corpse Pale",
                       ID_Num="WP1411"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Elven Flesh",
                       ID_Num="WP1421"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Mummy Robes",
                       ID_Num="WP1440"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Troll Claws",
                       ID_Num="WP1459"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Pixie Pink",
                       ID_Num="WP1447"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Scar Tissue",
                       ID_Num="WP1480"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Mutant Hue",
                       ID_Num="WP1441"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Toxic Boils",
                       ID_Num="WP1457"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Oozing Purple",
                       ID_Num="WP1445"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Alien Purple",
                       ID_Num="WP1128"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Chaotic Red",
                       ID_Num="WP1142"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Abomination Gore",
                       ID_Num="WP1401"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Vampire Red",
                       ID_Num="WP1460"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Dragon Red",
                       ID_Num="WP1105"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Pure Red",
                       ID_Num="WP1104"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Mars Red",
                       ID_Num="WP1436"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Lava Orange",
                       ID_Num="WP1106"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Mythical Orange",
                       ID_Num="WP1442"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Fire Lizard",
                       ID_Num="WP1426"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Phoenix Flames",
                       ID_Num="WP1446"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Daemonic Yellow",
                       ID_Num="WP1107"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Babe Blond",
                       ID_Num="WP1403"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Moon Dust",
                       ID_Num="WP1438"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Arid Earth",
                       ID_Num="WP1402"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Witch Brew",
                       ID_Num="WP1465"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Poisonous Cloud",
                       ID_Num="WP1448"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Jungle Green",
                       ID_Num="WP1433"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Snake Scales",
                       ID_Num="WP1453"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Goblin Green",
                       ID_Num="WP1109"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Greenskin",
                       ID_Num="WP1111"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Combat Fatigues",
                       ID_Num="WP1409"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Filthy Cape",
                       ID_Num="WP1424"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Army Green",
                       ID_Num="WP1110"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Commando Green",
                       ID_Num="WP1410"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Venom Wyrm",
                       ID_Num="WP1461"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Crypt Wraith",
                       ID_Num="WP1413"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Angel Green",
                       ID_Num="WP1112"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Elf Green",
                       ID_Num="WP1420"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Mouldy Clothes",
                       ID_Num="WP1439"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Scaly Hide",
                       ID_Num="WP1450"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Necrotic Flesh",
                       ID_Num="WP1108"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Drake Tooth",
                       ID_Num="WP1417"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Deep Blue",
                       ID_Num="WP1116"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Ultramarine Blue",
                       ID_Num="WP1115"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Viking Blue",
                       ID_Num="WP1462"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Crystal Blue",
                       ID_Num="WP1114"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Troglodyte Blue",
                       ID_Num="WP1458"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Voidshield Blue",
                       ID_Num="WP1452"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Toxic Mist",
                       ID_Num="WP1437"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Royal Cloak",
                       ID_Num="WP1449"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Hydra Turquoise",
                       ID_Num="WP1141"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Wizards Orb",
                       ID_Num="WP1466"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Elemental Bolt",
                       ID_Num="WP1419"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Kraken Skin",
                       ID_Num="WP1435"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Griffon Blue",
                       ID_Num="WP1429"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Electric Blue",
                       ID_Num="WP1113"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Ice Storm",
                       ID_Num="WP1432"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Gorgon Hide",
                       ID_Num="WP1428"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Fog Grey",
                       ID_Num="WP1427"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Wolf Grey",
                       ID_Num="WP1119"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Dark Sky",
                       ID_Num="WP1415"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Brush-On Primer",
                       ID_Num="WP1472"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Glistening Blood",
                       ID_Num="WP1476"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Dry Rust",
                       ID_Num="WP1479"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Wet Mud",
                       ID_Num="WP1478"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Disgusting Slime",
                       ID_Num="WP1477"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Military Shader",
                       ID_Num="WP1471"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Green Tone",
                       ID_Num="WP1137"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Purple Tone",
                       ID_Num="WP1140"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Blue Tone",
                       ID_Num="WP1139"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Dark Tone",
                       ID_Num="WP1136"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Strong Tone",
                       ID_Num="WP1135"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Soft Tone",
                       ID_Num="WP1134"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Red Tone",
                       ID_Num="WP1138"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Flesh Wash",
                       ID_Num="WP1143"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Mid Brown",
                       ID_Num="WP1469"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Light Tone",
                       ID_Num="WP1470"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Anti-Shine Matt Varnish",
                       ID_Num="WP1103"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Quickshade Wash Mixing Medium",
                       ID_Num="WP1474"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Warpaints Mixing Medium",
                       ID_Num="WP1475"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Gloss Varnish",
                       ID_Num="WP1473"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Oak Brown",
                       ID_Num="WP1124"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Monster Brown",
                       ID_Num="WP1120"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Dirt Spatter",
                       ID_Num="WP1416"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Werewolf Fur",
                       ID_Num="WP1464"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Leather Brown",
                       ID_Num="WP1123"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Sulfide Ochre",
                       ID_Num="WP1456"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Bright Gold",
                       ID_Num="WP1144"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Greedy Gold",
                       ID_Num="WP1132"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="True Cooper",
                       ID_Num="WP1467"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Weapon Bronze",
                       ID_Num="WP1133"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Shining Silver",
                       ID_Num="WP1129"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Plate Mail Metal",
                       ID_Num="WP1130"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Gun Metal",
                       ID_Num="WP1131"))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Rough Iron",
                       ID_Num="WP1468"))