'''
Created on 04.12.2017

@author: mabelli
'''

def createWPColors(t_Color, session, CompanyID, colorTypes):
    session.add(t_Color(C_ID=CompanyID,
                       Name="Matt Black",
                       ID_Num="WP1101",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Necromancer Cloak",
                       ID_Num="WP1443",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Hardened Carapace",
                       ID_Num="WP1430",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Dark Stone",
                       ID_Num="WP1425",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Cultist Robe",
                       ID_Num="WP1414",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Field Grey",
                       ID_Num="WP1481",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Castle Grey",
                       ID_Num="WP1407",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Dungeon Grey",
                       ID_Num="WP1418",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Uniform Grey",
                       ID_Num="WP1118",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Ash Grey",
                       ID_Num="WP1117",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Stone Golem",
                       ID_Num="WP1455",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Spaceship Exterior",
                       ID_Num="WP1454",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Brainmatter Beige",
                       ID_Num="WP1406",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Matt White",
                       ID_Num="WP1102",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Banshee Brown",
                       ID_Num="WP1404",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Kobold Skin",
                       ID_Num="WP1434",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Hemp Rope",
                       ID_Num="WP1433",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Crusted Sore",
                       ID_Num="WP1412",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Orc Blood",
                       ID_Num="WP1422",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Grimoire Purple",
                       ID_Num="WP1444",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Warlock Purple",
                       ID_Num="WP1451",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Wasteland Soil",
                       ID_Num="WP1463",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Desert Yellow",
                       ID_Num="WP1121",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Fur Brown",
                       ID_Num="WP1122",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Skeleton Bone",
                       ID_Num="WP1125",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Barbarian Flesh",
                       ID_Num="WP1126",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Tanned Flesh",
                       ID_Num="WP1127",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Basilisk Brown",
                       ID_Num="WP1405",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Centaur Skin",
                       ID_Num="WP1408",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Corpse Pale",
                       ID_Num="WP1411",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Elven Flesh",
                       ID_Num="WP1421",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Mummy Robes",
                       ID_Num="WP1440",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Troll Claws",
                       ID_Num="WP1459",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Pixie Pink",
                       ID_Num="WP1447",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Scar Tissue",
                       ID_Num="WP1480",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Mutant Hue",
                       ID_Num="WP1441",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Toxic Boils",
                       ID_Num="WP1457",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Oozing Purple",
                       ID_Num="WP1445",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Alien Purple",
                       ID_Num="WP1128",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Chaotic Red",
                       ID_Num="WP1142",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Abomination Gore",
                       ID_Num="WP1401",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Vampire Red",
                       ID_Num="WP1460",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Dragon Red",
                       ID_Num="WP1105",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Pure Red",
                       ID_Num="WP1104",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Mars Red",
                       ID_Num="WP1436",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Lava Orange",
                       ID_Num="WP1106",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Mythical Orange",
                       ID_Num="WP1442",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Fire Lizard",
                       ID_Num="WP1426",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Phoenix Flames",
                       ID_Num="WP1446",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Daemonic Yellow",
                       ID_Num="WP1107",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Babe Blond",
                       ID_Num="WP1403",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Moon Dust",
                       ID_Num="WP1438",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Arid Earth",
                       ID_Num="WP1402",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Witch Brew",
                       ID_Num="WP1465",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Poisonous Cloud",
                       ID_Num="WP1448",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Jungle Green",
                       ID_Num="WP1433",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Snake Scales",
                       ID_Num="WP1453",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Goblin Green",
                       ID_Num="WP1109",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Greenskin",
                       ID_Num="WP1111",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Combat Fatigues",
                       ID_Num="WP1409",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Filthy Cape",
                       ID_Num="WP1424",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Army Green",
                       ID_Num="WP1110",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Commando Green",
                       ID_Num="WP1410",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Venom Wyrm",
                       ID_Num="WP1461",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Crypt Wraith",
                       ID_Num="WP1413",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Angel Green",
                       ID_Num="WP1112",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Elf Green",
                       ID_Num="WP1420",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Mouldy Clothes",
                       ID_Num="WP1439",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Scaly Hide",
                       ID_Num="WP1450",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Necrotic Flesh",
                       ID_Num="WP1108",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Drake Tooth",
                       ID_Num="WP1417",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Deep Blue",
                       ID_Num="WP1116",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Ultramarine Blue",
                       ID_Num="WP1115",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Viking Blue",
                       ID_Num="WP1462",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Crystal Blue",
                       ID_Num="WP1114",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Troglodyte Blue",
                       ID_Num="WP1458",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Voidshield Blue",
                       ID_Num="WP1452",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Toxic Mist",
                       ID_Num="WP1437",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Royal Cloak",
                       ID_Num="WP1449",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Hydra Turquoise",
                       ID_Num="WP1141",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Wizards Orb",
                       ID_Num="WP1466",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Elemental Bolt",
                       ID_Num="WP1419",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Kraken Skin",
                       ID_Num="WP1435",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Griffon Blue",
                       ID_Num="WP1429",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Electric Blue",
                       ID_Num="WP1113",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Ice Storm",
                       ID_Num="WP1432",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Gorgon Hide",
                       ID_Num="WP1428",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Fog Grey",
                       ID_Num="WP1427",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Wolf Grey",
                       ID_Num="WP1119",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Dark Sky",
                       ID_Num="WP1415",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Brush-On Primer",
                       ID_Num="WP1472",
                       CT_ID = colorTypes[5].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Glistening Blood",
                       ID_Num="WP1476",
                       CT_ID = colorTypes[2].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Dry Rust",
                       ID_Num="WP1479",
                       CT_ID = colorTypes[2].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Wet Mud",
                       ID_Num="WP1478",
                       CT_ID = colorTypes[2].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Disgusting Slime",
                       ID_Num="WP1477",
                       CT_ID = colorTypes[2].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Military Shader",
                       ID_Num="WP1471",
                       CT_ID = colorTypes[3].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Green Tone",
                       ID_Num="WP1137",
                       CT_ID = colorTypes[3].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Purple Tone",
                       ID_Num="WP1140",
                       CT_ID = colorTypes[3].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Blue Tone",
                       ID_Num="WP1139",
                       CT_ID = colorTypes[3].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Dark Tone",
                       ID_Num="WP1136",
                       CT_ID = colorTypes[3].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Strong Tone",
                       ID_Num="WP1135",
                       CT_ID = colorTypes[3].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Soft Tone",
                       ID_Num="WP1134",
                       CT_ID = colorTypes[3].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Red Tone",
                       ID_Num="WP1138",
                       CT_ID = colorTypes[3].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Flesh Wash",
                       ID_Num="WP1143",
                       CT_ID = colorTypes[3].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Mid Brown",
                       ID_Num="WP1469",
                       CT_ID = colorTypes[3].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Light Tone",
                       ID_Num="WP1470",
                       CT_ID = colorTypes[3].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Anti-Shine Matt Varnish",
                       ID_Num="WP1103",
                       CT_ID = colorTypes[4].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Quickshade Wash Mixing Medium",
                       ID_Num="WP1474",
                       CT_ID = colorTypes[6].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Warpaints Mixing Medium",
                       ID_Num="WP1475",
                       CT_ID = colorTypes[6].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Gloss Varnish",
                       ID_Num="WP1473",
                       CT_ID = colorTypes[4].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Oak Brown",
                       ID_Num="WP1124",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Monster Brown",
                       ID_Num="WP1120",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Dirt Spatter",
                       ID_Num="WP1416",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Werewolf Fur",
                       ID_Num="WP1464",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Leather Brown",
                       ID_Num="WP1123",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Sulfide Ochre",
                       ID_Num="WP1456",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Bright Gold",
                       ID_Num="WP1144",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Greedy Gold",
                       ID_Num="WP1132",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="True Cooper",
                       ID_Num="WP1467",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Weapon Bronze",
                       ID_Num="WP1133",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Shining Silver",
                       ID_Num="WP1129",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Plate Mail Metal",
                       ID_Num="WP1130",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Gun Metal",
                       ID_Num="WP1131",
                       CT_ID = colorTypes[0].ID))
    session.add(t_Color(C_ID=CompanyID,
                       Name="Rough Iron",
                       ID_Num="WP1468",
                       CT_ID = colorTypes[0].ID))